## Collaborators

This is a list of NEFSC PAB’s collaborators. 

# Academic Institutions

### [Robots4Whales](https://robots4whales.whoi.edu/)

Robots4Whales is a WHOI program focused on engineering tools to better understand whale biology.  

### [SMAST](https://www.umassd.edu/smast/)

UMASS Dartmouth: School for marine science and technology 

### [WHOI](https://www.whoi.edu/)

Woods Hole Oceanographic Institute is a non-profit organization focused on cross-discipline marine studies.

# State Collaborators

### [Maine DMR](https://www.maine.gov/dmr/home)

Maine’s department of marine resources regulates the state’s commercial and recreational saltwater fisheries, and supports research ensuring the existence of future stocks. 

### [MASS DMF](https://www.mass.gov/orgs/division-of-marine-fisheries)

The Division of Marine Fisheries manages the state’s commercial and recreational saltwater fisheries and oversees other services that support the marine environment and fishing communities.

# Federal Collaborators

### [BOEM](https://www.boem.gov/)

The Bureau of Ocean Energy Management, a branch of the U.S. Department of the Interior, manages ocean energy development and resources while considering environmental and economic responsibility. 

### [Greater Atlantic Regional Fisheries Office](https://www.fisheries.noaa.gov/about/greater-atlantic-regional-fisheries-office)

GARFO leads stewardship efforts of living marine and diadromous resources in the Greater Atlantic Region, encompassing the Northwest Atlantic and Great Lakes region/watersheds. 

### [Navy Living Marine Resources](https://exwc.navfac.navy.mil/Products-and-Services/Environmental-Security/LMR/)

The Living Marine Resources Program supports Naval training by assessing potential impacts to marine species from Naval activities.

### [NOAA Fisheries Office of Protected Resources](https://www.fisheries.noaa.gov/about/office-protected-resources)

The Office of Protected Resources is responsible for the conservation, protection, and recovery of the nation’s endangered and threatened marine species under the endangered species act. PAB contributes to monitoring species status, notably monitoring the Atlantic right whale population.

### [NOAA Research PMEL](https://www.pmel.noaa.gov/) (Samara)

The Pacific Marine Environmental Laboratory conducts robust marine research globally. 

### [NOAA Fisheries Office of Science and Technology](https://www.fisheries.noaa.gov/about/office-science-and-technology)

The Office of Science and Technology advocates and ensures sound scientific basis for NOAA Fisheries science programs and resource conservation and management decisions. OST coordinates closely with NOAA’s regional science centers, including NEFSC.

### [Office of National Marine Sanctuary](https://sanctuaries.noaa.gov/)

The Office of National Marine Sanctuaries manages the nation’s marine sanctuaries including PAB’s primary study site; Stellwagen Bank Marine Sanctuary. 

### [Parks Australia](https://parksaustralia.gov.au/)

Parks Australia is a government organization which manages Australia’s national and marine parks. NEFSC PAB and Parks Australia collaborate to study the soundscapes of Australia’s \~60 marine parks. 

# NGO Collaborators

### [Atlantic States Marine Fisheries Commission](https://www.asmfc.org/)

ASMFC serves as a deliberative body of the Atlantic coastal states and coordinates the conservation and management of 27 nearshore fish species. The commission’s main policy arenas includes interstate fisheries management, fisheries science, habitat conservation, and law enforcement. 

### [Regional Wildlife Science Collaborative](https://rwsc.org/)

RWSC serves as a coordination hub for offshore wind research, with the goal of increasing collaboration, limiting redundancy, suggesting common data standards, and increasing data sharing and transparency. PAB supports monitoring specie interactions with offshore wind projects.

### [The Nature Conservancy](https://www.nature.org/en-us/)

The Nature Conservancy is a global environmental nonprofit conserving vital habitats. 



