---
title: Unidentified sounds
---

## Baleen

### Unidentified Baleen whale

**Scientific name:** *Balaeoptera sp.*\
**Makara code:** UNBA

### Unidentified Fin/Sei whale

**Scientific name**: *Balaenoptera physalus/bor*\
**Makara code:** UNFS

## Odontocete

### Unidentified Dolphin

**Scientific name:** *Delphinidae sp.*\
**Makara code:** UNDO

### Unidentified common dolphin

**Scientific name:** *Delphinus sp.*\
**Makara code:** DESP

### Unidentified Rissos/Bottlenose dolphin

**Scientific name:** *Tursiops/Grampus*\
**Makara code:** UNRB

### Unidentified Eastern/Central American Spinner dolphin

**Scientific name:** *Stenella longirostris*\
**Makara code:** UECASD

### Unidentified Pilot Whale

**Scientific name:** *Globicephala sp.*\
**Makara code:** PIWH

### Unidentified Blackfish species

**Makara code:** UNBF

### Unidentified True's/Gervais Beaked whale

**Scientific name:** *Mesoplodon mirus/europaeus*\
**Makara code:** MMME

### Unidentified Beaked whale

**Scientific name:** *Ziphiidae sp.*\
**Makara code:** UNBW

### Unidentified Narrow Band High Frequency Call

**Makara code:** NBHF

### Unidentified Pygmy/Dwarf Sperm Whale

**Scientific name:** *Kogia sp.*\
**Makara code:** UNKO


## Fish

### Unidentified Fish

**Makara code:** UNFI

## Pinniped

### Unidentified Pinniped

**Makara code:** PINN

## Environment

### Unidentified Environment 

**Makara code:** UNEN

## Anthropogenic 

### Unidentified Boat/Vessel

**Makara code:** UNVE

### Unidentified Anthropogenic

**Makara code:** UNAN

## Soundscape
Anthropogenic, environmental and other non-biological sounds

### Non-biological

**Makara code:** NONBIO
