---
title: "PAB Alumni"
page-layout: full
editor: 
  markdown: 
    wrap: 72
---

## Staff Alumni

Renea Briner (2023-2026)\
Dr. Julia Zeh (2024-2026)\
Murali Mood (2022-2026)\
Annabel Westell (2020-2026)\
Lindsey Transue (2022-2026)\
Sophie Ferguson (2023-2026)\
Michael Ryan (2023-2025)\
Maricarmen Serna (2024-2025)\
Dr. Timothy Rowell (2018-2023)\
Sara Tennant (2022-2023)\
Logan Kline (2019-2023)\
Jennifer Wallace (2019-2022)\
Molly Martin (2021-2022)\
Liam Mueller-Brennan (2019-2021)\
Nicole Pegg (2019-2021)\
Allison Stokoe (2019-2021)\
Dr. Danielle Cholewiak (2011-2020)\
Dr. Jenni Stanley (2015-2020)\
Dr. Paul Caiger (2017-2020)\
Dana Gerlach (2014-2020)\
Katharine Shelledy (2017-2019)\
Alyssa Scott (2019)\
Sarah Weiss (2017-2019)\
Grace Simpkins (2012-2018)\
Julianne Gurnee (now Wilder) (2015-2018)\
John Luke Palka (2018)\
Megan Slack (2018)\
Christopher Tremblay (2015-2016)\
Samara Haver (2011-2015)\
Dr. Steven Brady (2013-2014)\
Keith Hernandez (2011-2012)\
Sarah Mussoline (2010-2012)\
Joy Stanistreet (2009-2011)\
Jillian Vitacco (2010)\
Elizabeth Vu (2008-2009)

## Students and Interns

### PhD Students

Dr. Samara Haver (2021)\
Dr. Genevieve Davis (2020)\
Dr. Joy Stanistreet (2017)\
Dr. Heather Heenehan (2016)\
Dr. Trudi Webster (2015)\
Dr. Denise Risch (2013)\
Dr. Robert Valtierra (2013)\
Dr. Ilse Van Opzeeland (2010)

### Interns

Anastasia Ippolito (Hollings 2026)\
Eleni Mouyos (Hollings 2026)\
Jayde Waibel (Hollings 2026)\
Kaitlyn Ho (Three Seas MS 2025)\
Jamie Fogg (Hollings 2025)\
Samantha Kratman (Hollings 2025)\
Miles Lubas (Hollings 2025)\
Madison Medina (Hollings 2024)\
Rose Nolan (Hollings 2024)\
Peyton Steffek (Hollings 2024)\
Sophie Strock (Hollings 2024)\
Taylor Coleman (2024)\
Emily Barnes (now Noonan) (HS 2023-2024)\
Brijonnay Madrigal (Nancy Foster Scholar 2023)\
Cassidy Beach (Hollings 2023)\
Matthew Brander (Hollings 2023)\
Abigail Fritz (Hollings 2023)\
Isabella Garfield (Hollings 2023)\
Alexandra Redford (Hollings 2023)\
Zoie Bright (Hollings 2022)\
Sophia Zoll (Hollings 2022)\
Sara Tennant (Three Seas MS 2022)\
Anne Smith (2022)\
Sonia Liu (2022)\
Noah Laber (2022)\
Nicholas Hayes (Hollings 2021)\
Korianna Hays (Hollings 2021)\
Jabari Lottie (PEP 2021)\
Paul Ernst (Hollings 2020)\
Kristen McCauley (PEP 2020)\
Meredith Sackett (MS 2020)\
Natasha Heisenberg (HS 2018-2019)\
Caroline Reed (HS 2018-2019)\
Logan Kline (Hollings 2018)\
Dawn Perry (Hollings 2018)\
Nicole Pegg (Hollings 2018)\
Zachary Pinard (Hollings 2018)\
Bridget Mueller-Brennan (Hollings 2017)\
Megan Sullivan (Hollings 2017)\
Sandra Dorning (Hollings 2016)\
Alyssa Scott (Hollings 2016)\
Katharine Shelledy (Hollings 2016)\
Sarah Weiss (2016)\
Daniel Woodrich (Hollings 2015)\
Sabena Siddiqui (2015)\
Alisa Young (PEP 2014)\
Julianne Cossavella (MS 2014)\
Julianne Gurnee (now Wilder) (Hollings 2013)\
Sam Hommand (2013)\
Julia Luthringer (Hollings 2012)\
Myya Jackson (PEP 2012)\
Danielle Rodriguez (PEP 2012)\
James Lewis (PEP 2011)\
Sarah Strobel (2011)\
Samara Haver (2011)\
Lauren Gentile (2010-2011)\
Caitlin Waring (HS 2010-2011)\
Genevieve Davis (Hollings 2010)\
Keith Hernandez (Hollings 2010)\
DeBie Dunn (EPP 2010)\
Rachel Rochon (PEP 2010)\
Jackie Koo (HS 2009-2010)\
Taryn Overton (Hollings 2009)\
Michelle McEachern (Hollings 2009)\
Jordan Aoyama (PEP 2009)\
Gabriel Poritz (2009)\
Andre Guerreiro da Silva (2008-2009)\
Amy Rhoads (Hollings 2008)\
Joy Stanistreet (Hollings 2008)\
Sarah Mussoline (Hollings 2007)\
Elizabeth Vu (Hollings 2007)\
Shonda Gaylord (Hollings 2007)\
Jackie Kiernan (2006-2007)\
Rachael Dickey (Hollings 2006)\
Charles White (Hollings 2006)\
